Better readability and copy symlinks also for backup-config.

diff --git a/backup-config b/backup-config
--- a/backup-config
+++ b/backup-config
@@ -9,25 +9,27 @@ shift 1
 
 set -eo pipefail
 
-CONFIG_FILE="$HOME/.bin/backup-config.conf"
 
-if [ ! -d ${VOLUMES_DIR}/${VOLUME} ]; then
-    echo "Volume ${VOLUME} is not mounted. Please mount a volume named ${VOLUME} and try again."
-    exit 1
-fi
+# Set initial variables
 
-SUDO=$(which sudo)
-RSYNC=$(which rsync)
 AWK=$(which awk)
+CONFIG_FILE="$HOME/.bin/backup-config.conf"
+DATE="$(date +%d-%m-%Y)"
+PATH_ON_VOLUME="${VOLUMES_DIR}/${VOLUME}/${DATE}${HOME}/"
+RSYNC=$(which rsync)
+SUDO=$(which sudo)
+
+
+## Check if we have the required commands
 
 [ -z "${SUDO}" ] && echo "The command sudo is required to be installed to run backup-config."
 [ -z "${RSYNC}" ] && echo "The command rsync is required to be installed to run backup-config."
 [ -z "${AWK}" ] && echo "The command awk is required to be installed to run backup-config."
 
-DATE="$(date +%d-%m-%Y)"
-VOLUME_PATH="${VOLUMES_DIR}/${VOLUME}/${DATE}${HOME}/"
 
-echo "Sudo privileges are required to run this command."
+## Check privileges
+
+echo "Super user privileges are required to run this command."
 
 sudo --validate
 
@@ -37,28 +39,47 @@ if [ $? -ne 0 ]; then
     exit ${EXIT}
 fi
 
+
+# Check if the volume is mounted
+
+if [ ! -d ${VOLUMES_DIR}/${VOLUME} ]; then
+    echo "Volume ${VOLUME} is not mounted. Please mount a volume named ${VOLUME} and try again."
+    exit 1
+fi
+
+
+# Execute backup
+
 echo -e "\nStarting backup..\n"
 
-sudo mkdir -pv ${VOLUME_PATH}
+sudo mkdir -pv ${PATH_ON_VOLUME}
 
 while read -r PATH; do
-    BACKUP_PATH="${PATH/~\//${VOLUME_PATH}}"
+
+    TARGET_PATH="${PATH/~\//${PATH_ON_VOLUME}}"
     PATH="${PATH/~\//${HOME}/}"
 
-    if ([ ! -e ${PATH} ] || [ -L ${PATH} ] || [ -h ${PATH} ] || [ -S ${PATH} ]); then
+	# Check if the file exists and is not a special file or socket
+    if ([ ! -e ${PATH} ] || [ -b ${PATH} ]|| [ -c ${PATH} ] || [ -S ${PATH} ]); then
 		continue
 	fi
 
+    # Copy directories recursively
 	if [ -d ${PATH} ]; then
-		PRE_DIR=$(echo "${BACKUP_PATH}" | ${AWK} 'BEGIN{FS=OFS="/"} {NF--} 1')
-		#[ ! -d ${BACKUP_PATH} ] && ${SUDO} /bin/mkdir -pv ${BACKUP_PATH}
-		${SUDO} ${RSYNC} -riam --sparse --update --perms --out-format="%o (%l bytes) | %f --> ${PRE_DIR}/%n" --prune-empty-dirs ${PATH} ${PRE_DIR/}
+		DIR=$(echo "${TARGET_PATH}" | ${AWK} 'BEGIN{FS=OFS="/"} {NF--} 1')
+		${SUDO} ${RSYNC} -riam --sparse --update --perms --out-format="[%t] %o %f --> ${DIR}/%n (%l bytes)" --prune-empty-dirs ${PATH} ${DIR/}
 	fi
 
+    # Copy files
 	if [ -f ${PATH} ]; then
-		PATH_DIR=$(echo "${BACKUP_PATH}" | ${AWK} 'BEGIN{FS=OFS="/"} {NF--} 1')
-		#[ ! -d ${PATH_DIR} ] && ${SUDO} /bin/mkdir -pv ${PATH_DIR}
-		${SUDO} ${RSYNC} -ria --sparse --update --perms --out-format="%o (%l bytes) | %f --> ${PATH_DIR}/%n/" ${PATH} ${PATH_DIR}/
+		DIR=$(echo "${TARGET_PATH}" | ${AWK} 'BEGIN{FS=OFS="/"} {NF--} 1')
+		${SUDO} ${RSYNC} -ria --sparse --update --perms --out-format="[%t] %o %f --> ${DIR}/%n (%l bytes)" ${PATH} ${DIR}/
+	fi
+
+    # Copy symlinks
+	if [ -h ${PATH} ]; then
+		DIR=$(echo "${TARGET_PATH}" | ${AWK} 'BEGIN{FS=OFS="/"} {NF--} 1')
+		${SUDO} ${RSYNC} -ria --links --sparse --update --perms --out-format="[%t] %o %f --> ${DIR}/%n (%l bytes)" ${PATH} ${DIR}/
 	fi
 
 done <$CONFIG_FILE
